### ISSUE TITLE
user defines input variables

### ISSUE THREAD

**Issue by SjoerdHilhorst** [SjoerdHilhorst/power-simulation#23]
# currently

user can only define functions for active and reactive power. this already gives some flexibility, but when a user maybe has a functions for ```voltage_l1_l2, voltage_l2_l3``` etc he is not able to input this in the environment file, or has to rewrite the function so that it calculates ```active, reactive power```.

# Enhancement
make it available for user to define which fields he wants as input variables. something like how i did choosing fields for graph. This way the user has more options, and isn't restricted by the hardcoded input fields for defining functions

# Implications
I do not really know if this is really feasible because the user has to define a complete list of functions. From which the relational fields will be calculated, otherwise some things can't be calculated at all

**Comment by m-ariya** [comment]
Is it the way to put in dictionary lambda functions for all fields (or at least the ones which possibly might be changed)? I hope I understood you correctly, cause I m a bit confused with this phrasing ‘he is not able to input this in the environment file, or has to rewrite the function’
