### ISSUE TITLE
Fields dictionary format

### ISSUE THREAD

**Issue by m-ariya** [SjoerdHilhorst/power-simulation#39]
I'm changing the field definition to dictionaries and I suggest this format:
`'fields': {
        'soc': {'reg_type': holding, 'address': 10, 'encode': [scale, int32]},
}`
So the type of storage (scale/comb) and the type of field (32bit int/ 32bit float etc) are under same key. Please let me know if you agree with it.

**Comment by SjoerdHilhorst** [comment]
looks good, maybe do for integers probably best if we have unsigned and signed, uint, sint. and maybe caps? so ``UINT32```

**Comment by m-ariya** [comment]
These are the options which I considered:
`int8 = 'int8'
uint8 = 'int8'
int16 = 'int16'
uint16 = 'uint16'
float32 = 'float32'
int32 = 'int32'
uint32 = 'uint32'`

but yeah, I can change it to caps

**Comment by SjoerdHilhorst** [comment]
:+1:
