### ISSUE TITLE
unit test fail

### ISSUE THREAD

**Issue by chrisw889** [SjoerdHilhorst/power-simulation#63]
I created all the tests for the payload handler but one of them is failing and I can't figure out why. it adds the number to the modbus store 1000 and since the decoder is using scale it should output 1 but it's getting 65536. Clearly this is nowhere near right. Can anyone maybe see where this is going wrong? just run the test_util file to see where it fails.

**Comment by m-ariya** [comment]
could you at least tell which line is it?

**Comment by chrisw889** [comment]
Line 131 is the assert that fails

**Comment by chrisw889** [comment]
still at a complete loss to what's causing the test to fail

**Comment by chrisw889** [comment]
removed failing tests as what they were testing is already covered by other tests.
